version: '3.9'

services:
  app:
    build: .
    restart: always
    networks:
      - app-network
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
  postgres:
    image: postgres:14-alpine
    restart: always
    networks:
      - app-network
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - app-volume:/app

networks:
  app-network:

volumes:
  app-volume: