version: '3.9'

services:
  auth:
    build: 
      context: .
      args: 
        SERVICE_NAME: "auth"
    restart: always
    networks:
      - app-network
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    depends_on:
      - postgres
      - rabbitmq

  meetups:
    build: 
      context: .
      args: 
        SERVICE_NAME: "meetups"
    restart: always
    networks:
      - app-network
    ports:
      - "${MEETUPS_PORT}:${MEETUPS_PORT}"
    depends_on:
      - postgres
      - rabbitmq

  gateway:
    build: 
      context: .
      args: 
        SERVICE_NAME: "gateway"
    restart: always
    networks:
      - app-network
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    depends_on:
      - meetups
      - auth
  
  postgres:
    image: postgis/postgis
    restart: always
    networks:
      - app-network
    ports:
      - "${DB_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - app-volume:/app
    depends_on:
      - rabbitmq
  
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "${RABBIT_PORT}:${RABBIT_PORT}"
      - "${WEB_RABBIT_PORT}:${WEB_RABBIT_PORT}"
    networks:
      - app-network

  elasticsearch:
    image: elasticsearch:7.8.1
    ports:
      - 9200:9200
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}

  kibana:
    image: kibana:7.8.1
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601

networks:
  app-network:
  elastic:

volumes:
  app-volume: