version: '3.9'

services:
  auth:
    build: 
      context: .
      args: 
        SERVICE_NAME: "auth"
    restart: always
    networks:
      - app-network
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    depends_on:
      - postgres
      - rabbitmq
 
  meetups:
    build: 
      context: .
      args: 
        SERVICE_NAME: "meetups"
    restart: always
    networks:
      - app-network
    ports:
      - "${MEETUPS_PORT}:${MEETUPS_PORT}"
    depends_on:
      - postgres
      - rabbitmq

  gateway:
    build: 
      context: .
      args: 
        SERVICE_NAME: "gateway"
    restart: always
    networks:
      - app-network
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    depends_on:
      - meetups
      - auth
  
  postgres:
    image: postgres:14-alpine
    restart: always
    networks:
      - app-network
    ports:
      - "${DB_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - app-volume:/app
    depends_on:
      - rabbitmq
  
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "${RABBIT_PORT}:${RABBIT_PORT}"
      - "${WEB_RABBIT_PORT}:${WEB_RABBIT_PORT}"
    networks:
      - app-network

networks:
  app-network:

volumes:
  app-volume: